// flow-typed signature: 5c324d4fd3494578e97f4149ff6fff13
// flow-typed version: <<STUB>>/eslint-config-mango_v^1.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mango'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mango' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-mango/index' {
  declare module.exports: $Exports<'eslint-config-mango'>;
}
declare module 'eslint-config-mango/index.js' {
  declare module.exports: $Exports<'eslint-config-mango'>;
}
