// flow-typed signature: 4b07b805b6f1f5681804551ac40090f0
// flow-typed version: <<STUB>>/popper.js_v1.12.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'popper.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'popper.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'popper.js/dist/esm/popper-utils' {
  declare module.exports: any;
}

declare module 'popper.js/dist/esm/popper-utils.min' {
  declare module.exports: any;
}

declare module 'popper.js/dist/esm/popper' {
  declare module.exports: any;
}

declare module 'popper.js/dist/esm/popper.min' {
  declare module.exports: any;
}

declare module 'popper.js/dist/popper-utils' {
  declare module.exports: any;
}

declare module 'popper.js/dist/popper-utils.min' {
  declare module.exports: any;
}

declare module 'popper.js/dist/popper' {
  declare module.exports: any;
}

declare module 'popper.js/dist/popper.min' {
  declare module.exports: any;
}

declare module 'popper.js/dist/umd/popper-utils' {
  declare module.exports: any;
}

declare module 'popper.js/dist/umd/popper-utils.min' {
  declare module.exports: any;
}

declare module 'popper.js/dist/umd/popper' {
  declare module.exports: any;
}

declare module 'popper.js/dist/umd/popper.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'popper.js/dist/esm/popper-utils.js' {
  declare module.exports: $Exports<'popper.js/dist/esm/popper-utils'>;
}
declare module 'popper.js/dist/esm/popper-utils.min.js' {
  declare module.exports: $Exports<'popper.js/dist/esm/popper-utils.min'>;
}
declare module 'popper.js/dist/esm/popper.js' {
  declare module.exports: $Exports<'popper.js/dist/esm/popper'>;
}
declare module 'popper.js/dist/esm/popper.min.js' {
  declare module.exports: $Exports<'popper.js/dist/esm/popper.min'>;
}
declare module 'popper.js/dist/popper-utils.js' {
  declare module.exports: $Exports<'popper.js/dist/popper-utils'>;
}
declare module 'popper.js/dist/popper-utils.min.js' {
  declare module.exports: $Exports<'popper.js/dist/popper-utils.min'>;
}
declare module 'popper.js/dist/popper.js' {
  declare module.exports: $Exports<'popper.js/dist/popper'>;
}
declare module 'popper.js/dist/popper.min.js' {
  declare module.exports: $Exports<'popper.js/dist/popper.min'>;
}
declare module 'popper.js/dist/umd/popper-utils.js' {
  declare module.exports: $Exports<'popper.js/dist/umd/popper-utils'>;
}
declare module 'popper.js/dist/umd/popper-utils.min.js' {
  declare module.exports: $Exports<'popper.js/dist/umd/popper-utils.min'>;
}
declare module 'popper.js/dist/umd/popper.js' {
  declare module.exports: $Exports<'popper.js/dist/umd/popper'>;
}
declare module 'popper.js/dist/umd/popper.min.js' {
  declare module.exports: $Exports<'popper.js/dist/umd/popper.min'>;
}
