// flow-typed signature: a0b814bff552717f502f721499769fcb
// flow-typed version: <<STUB>>/tristicons_vhttps://github.com/mango-chutney/tristicons/archive/81ef6d51d8ea06fafe83a584e33b7b94183e8409.tar.gz/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tristicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tristicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tristicons/scripts/get-base64-respresentations' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tristicons/index' {
  declare module.exports: $Exports<'tristicons'>;
}
declare module 'tristicons/index.js' {
  declare module.exports: $Exports<'tristicons'>;
}
declare module 'tristicons/scripts/get-base64-respresentations.js' {
  declare module.exports: $Exports<'tristicons/scripts/get-base64-respresentations'>;
}
